/**
 * @module schemas
 * @layer Core / Model
 * @description Zod validation schemas for all domain entities.
 * Every piece of data entering the system MUST be parsed through these schemas.
 *
 * Boundary validation points:
 *   - Import: raw JSON → ExportManifestSchema.parse()
 *   - Storage reads: IndexedDB row → TagSchema.parse()
 *   - User input: form data → CreateTagInputSchema.parse()
 */

import { z } from 'zod';
import {
  TAG_NAME_MAX_LENGTH,
  TAG_NOTES_MAX_LENGTH,
  TAG_COLOR_MAX_INDEX,
  TAG_COLOR_MIN_INDEX,
  CURRENT_SCHEMA_VERSION,
} from '@core/shared/constants';

// ─── Tag Source ───────────────────────────────────────────────────────────────

export const TagSourceSchema = z.discriminatedUnion('type', [
  z.object({ type: z.literal('local') }),
  z.object({
    type: z.literal('imported'),
    origin: z.string().max(200),
    importedAt: z.number().int().positive(),
  }),
]);

// ─── Tag ─────────────────────────────────────────────────────────────────────

export const TagSchema = z.object({
  id: z.string().uuid(),
  name: z
    .string()
    .min(1, 'Tag name cannot be empty')
    .max(TAG_NAME_MAX_LENGTH, `Tag name must be ${TAG_NAME_MAX_LENGTH} characters or fewer`)
    .trim(),
  colorIndex: z
    .number()
    .int()
    .min(TAG_COLOR_MIN_INDEX)
    .max(TAG_COLOR_MAX_INDEX, `Color index must be 0–${TAG_COLOR_MAX_INDEX}`),
  notes: z
    .string()
    .max(TAG_NOTES_MAX_LENGTH, `Notes must be ${TAG_NOTES_MAX_LENGTH} characters or fewer`)
    .optional(),
  source: TagSourceSchema,
  createdAt: z.number().int().positive(),
  updatedAt: z.number().int().positive(),
  deletedAt: z.number().int().positive().optional(),
});

export type TagSchemaType = z.infer<typeof TagSchema>;

// ─── User Identifier ─────────────────────────────────────────────────────────

export const UserIdentifierSchema = z.object({
  platform: z.string().min(1),
  username: z.string().min(1).max(50),
  platformId: z.string().optional(),
  displayName: z.string().max(100).optional(),
  avatarUrl: z.string().url().optional(),
  firstSeen: z.number().int().positive(),
  lastSeen: z.number().int().positive(),
});

// ─── Export Manifest ─────────────────────────────────────────────────────────

const CollectionCriteriaSchema = z.object({
  name:           z.string().min(1).max(100),
  includeAnyTags: z.array(z.string()).default([]),
  includeAllTags: z.array(z.string()).default([]),
  excludeTags:    z.array(z.string()).default([]),
});

export const ExportManifestSchema = z.object({
  schemaVersion: z
    .number()
    .int()
    .min(1)
    .max(CURRENT_SCHEMA_VERSION + 10, 'Schema version too far in the future'),
  exportedAt:  z.string().datetime(),
  exportedBy:  z.string().max(100).optional(),
  description: z.string().max(500).optional(),
  collection:  CollectionCriteriaSchema.optional(),
  platform:    z.string().min(1),
  checksum:    z.string().length(64, 'Checksum must be a 64-char SHA-256 hex digest'),
  entries:     z.record(z.string(), z.array(TagSchema)),
});

export type ExportManifestSchemaType = z.infer<typeof ExportManifestSchema>;

// ─── Settings ────────────────────────────────────────────────────────────────

export const DisplayModeSchema = z.enum(['compact', 'pills', 'full', 'hidden']);

export const ExtensionSettingsSchema = z.object({
  displayMode: DisplayModeSchema,
  theme: z.enum(['auto', 'light', 'dark']),
  hoverToEdit: z.boolean(),
  extendedPalette: z.boolean(),
  surfaceOverrides: z.record(z.string(), DisplayModeSchema),
});

// ─── User Input DTOs ─────────────────────────────────────────────────────────

/** Input for creating a new tag — id, createdAt, updatedAt are generated by service */
export const CreateTagInputSchema = z.object({
  name: z
    .string()
    .min(1, 'Tag name cannot be empty')
    .max(TAG_NAME_MAX_LENGTH)
    .trim(),
  colorIndex: z.number().int().min(0).max(TAG_COLOR_MAX_INDEX),
  notes: z.string().max(TAG_NOTES_MAX_LENGTH).optional(),
});

export type CreateTagInput = z.infer<typeof CreateTagInputSchema>;

/** Input for updating an existing tag — all fields optional except id */
export const UpdateTagInputSchema = z.object({
  id: z.string().uuid(),
  name: z.string().min(1).max(TAG_NAME_MAX_LENGTH).trim().optional(),
  colorIndex: z.number().int().min(0).max(TAG_COLOR_MAX_INDEX).optional(),
  notes: z.string().max(TAG_NOTES_MAX_LENGTH).optional(),
});

export type UpdateTagInput = z.infer<typeof UpdateTagInputSchema>;

// ─── Import Filter ────────────────────────────────────────────────────────────

/** Options controlling how an import is applied */
export const ImportOptionsSchema = z.object({
  /** How to handle tags with the same name for the same user */
  conflictStrategy: z.enum(['keep-mine', 'keep-theirs', 'merge-both']),
  /** Only import users whose username matches these values (empty = import all) */
  filterUsernames: z.array(z.string()).default([]),
  /** Only import tags with these names (empty = import all) */
  filterTagNames: z.array(z.string()).default([]),
});

export type ImportOptions = z.infer<typeof ImportOptionsSchema>;
